import { test, expect } from '@playwright/test';

// SEO is a primary product concern for a content site (organic discovery is the
// whole funnel). These assert the structural metadata is present and correct,
// plus the theme system boots without a flash and persists.

test.describe('SEO metadata', () => {
  test('home page exposes canonical, OG, and a valid JSON-LD graph', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator('link[rel="canonical"]')).toHaveCount(1);
    await expect(page.locator('meta[property="og:title"]')).toHaveCount(1);
    await expect(page.locator('meta[property="og:image"]')).toHaveCount(1);

    const blocks = await page.locator('script[type="application/ld+json"]').allTextContents();
    expect(blocks.length).toBeGreaterThan(0);
    for (const block of blocks) {
      expect(() => JSON.parse(block), 'every JSON-LD block must be valid JSON').not.toThrow();
      // The XSS guard escapes "<" → the raw sequence must never appear inline.
      expect(block).not.toContain('</script>');
    }
  });

  test('lesson detail declares hreflang alternates for ar/en/x-default', async ({ page }) => {
    await page.goto('/lessons');
    await page.locator('a[href*="/lessons/"]').first().click();
    await expect(page.locator('link[rel="alternate"][hreflang="ar"]')).toHaveCount(1);
    await expect(page.locator('link[rel="alternate"][hreflang="en"]')).toHaveCount(1);
    await expect(page.locator('link[rel="alternate"][hreflang="x-default"]')).toHaveCount(1);
  });

  test('robots and sitemap are reachable', async ({ page }) => {
    expect((await page.goto('/robots.txt'))?.status()).toBe(200);
    expect((await page.goto('/sitemap.xml'))?.status()).toBe(200); // generated by scripts/generate-seo.mjs
  });
});

test.describe('theme', () => {
  test('boots to a resolved theme attribute before paint (no FOUC)', async ({ page }) => {
    await page.goto('/');
    const resolved = await page.locator('html').getAttribute('data-resolved-theme');
    expect(['light', 'dark']).toContain(resolved);
  });

  test('toggling theme persists the choice across reloads', async ({ page }) => {
    await page.goto('/');
    const toggle = page.getByRole('button', { name: /theme|الوضع|mode/i }).first();
    test.skip(!(await toggle.count()), 'theme toggle not found');
    const before = await page.locator('html').getAttribute('data-resolved-theme');
    await toggle.click();
    // Some toggles cycle system→light→dark; click until the resolved theme flips.
    for (let i = 0; i < 3; i++) {
      const now = await page.locator('html').getAttribute('data-resolved-theme');
      if (now !== before) break;
      await toggle.click();
    }
    const after = await page.locator('html').getAttribute('data-resolved-theme');
    expect(after).not.toBe(before);

    await page.reload();
    const persisted = await page.locator('html').getAttribute('data-resolved-theme');
    expect(persisted).toBe(after); // survived the reload via localStorage
  });

  test('a tampered localStorage theme value falls back to "system" (guard holds)', async ({
    page,
  }) => {
    await page.addInitScript(() => {
      try {
        window.localStorage.setItem('arabsyntax-theme', '"><script>alert(1)</script>');
      } catch {
        /* ignore */
      }
    });
    await page.goto('/');
    // isThemeChoice rejects the garbage → data-theme normalizes to "system".
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'system');
  });
});
